platform: maven

ports:
- 8080:80

cmd:
  start: java -jar webapps/echo-0.0.1-SNAPSHOT.jar

maven:
  build_task: clean package -Dmaven.test.skip=true -f pom.xml
  use_tomcat: true
  target:
  - target/*.jar

envs:
  _JAVA_OPTIONS: "-Xmx4096m -Xms4096m"

line.bot:
  channel-token: '1600817471'
  channel-secret: '792cde9ef1b4e092ae4f082d607414a7'
  handler.path: /callback